import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransitionEvent from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const JetBrain = JetBrains_Mono({
  subsets: ["latin"],
  weights: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--fontJetBrain",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` max-w-[1220px] mx-auto  ${JetBrain.variable}`}>
        <Header />
        <StairTransition />
        <PageTransitionEvent>{children}</PageTransitionEvent>
      </body>
    </html>
  );
}
